language: objective-c
osx_image: xcode7.3
script:
    - xcodebuild clean -workspace "Zeeguu Reader/Zeeguu Reader.xcworkspace" -scheme "Zeeguu Reader" | xcpretty
    - set -o pipefail && xcodebuild test -workspace "Zeeguu Reader/Zeeguu Reader.xcworkspace" -scheme "Zeeguu Reader" -destination 'platform=iOS Simulator,name=iPad Air 2' | xcpretty

